name: Build GDUtils

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
          - name: macOS
            os: macos-latest
          - name: Android32
            os: ubuntu-latest
            target: Android32
          - name: Android64
            os: ubuntu-latest
            target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          
      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true
          target: ${{ matrix.config.target }}
          export-pdb: true

  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      - name: Combine build outputs
        uses: geode-sdk/build-geode-mod/combine@main
        id: build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GDUtils Build Output
          path: ${{ steps.build.outputs.build-output }}
